services:
  shop-db:
    image: mysql:latest
    container_name: shop-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./env/.env.local
    volumes:
      - my-prod-app:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-app
  backend:
    build:
      context: ../
      dockerfile: ./.configs/nest.Dockerfile
    env_file: ./env/.env.local
    ports:
      - "2000:2000"
    networks:
      - my-app
    depends_on:
      - shop-db
    restart: unless-stopped
volumes:
  my-prod-app:
networks:
  my-app:
    name: my-app-network
    driver: bridge
