name: PR
run-name: ${{ github.actor }}  ${{ github.event_name }} event on ${{ github.name }}🚀
on:
  pull_request:
    branches:
      - main
jobs:
  premerge:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: lint+prettier
        run: npm run precommit
