name: Push
run-name: ${{ github.actor }}  ${{ github.event_name }} event on ${{ github.name }}🚀
on: [push]
jobs:
  prepush:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - run: npm run precommit
